# Generated by Django 4.2.4 on 2023-08-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.TextField(max_length=300)),
                ('reported_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
