# Generated by Django 4.2.4 on 2023-08-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=10)),
                ('count', models.IntegerField()),
                ('join_date', models.DateTimeField()),
                ('in_date', models.DateField()),
                ('out_date', models.DateField()),
            ],
        ),
    ]
