# Generated by Django 4.2.4 on 2023-08-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('Sangmudae', '상무대')], default='Sangmudae', max_length=10),
        ),
    ]
