# Generated by Django 4.2.4 on 2023-08-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='join_date',
            field=models.DateTimeField(),
        ),
    ]
