# Generated by Django 4.2.4 on 2023-08-05 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_count_alter_customuser_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='in_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='out_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
