# Generated by Django 4.2.4 on 2023-08-05 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_in_date_alter_customuser_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
