# Generated by Django 4.2.4 on 2023-08-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kakaoId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
