# Generated by Django 4.2.4 on 2023-08-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kakao_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Kakao Id'),
        ),
    ]
