# Generated by Django 4.2.4 on 2023-08-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='content',
            field=models.CharField(max_length=30),
        ),
    ]
